---
- name: Clean dnf RHEL8
  become: true
  command: dnf clean all -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Disable dnf module for RHEL8
  become: true
  command: dnf module disable postgresql -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Disable llvm-toolset dnf module for RHEL8
  become: true
  command: dnf module disable llvm-toolset -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: setup epel release
  yum:
    name: epel-release
    update_cache: yes
    state: present

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Percona Platform for PostgreSQL rpm packages for RHEL and additional tools
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-server-dev-all
    - percona-postgresql13
    - percona-postgresql13-contrib
    - percona-postgresql13-devel
    - percona-postgresql13-libs
    - percona-postgresql13-plpython3
    - percona-postgresql13-pltcl
    - percona-postgresql13-server
    - openssl-devel
    - etcd
    - python3-python-etcd
    - haproxy

- name: Install patroni RPM
  yum:
    name: percona-patroni
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Create /etc/patroni directory
  file:
    path: /etc/patroni
    state: directory

- name: Create test patroni directory
  file:
    path: /var/lib/pgsql/patroni_test/
    state: directory
    owner: postgres
    group: postgres

- name: Copy postgresql0.yml for patroni service
  copy:
    src: postgresql0.yml
    dest: /etc/patroni/postgresql.yml
    owner: root
    group: root
    mode: 0644

- name: Copy postgresql1.yml for patroni service
  copy:
    src: postgresql1.yml
    dest: /var/lib/pgsql/patroni_test/postgresql1.yml
    owner: postgres
    group: postgres
    mode: 0644

- name: Copy postgresql2.yml for patroni service
  copy:
    src: postgresql2.yml
    dest: /var/lib/pgsql/patroni_test/postgresql2.yml
    owner: postgres
    group: postgres
    mode: 0644

- name: Start etcd
  service:
    name: etcd
    state: started
    enabled: yes

- name: Start patroni
  service:
    name: patroni
    state: started
    enabled: yes

- name: Start patroni postgresql1 from shell
  shell: patroni patroni_test/postgres1.yml &
  become_user: postgres
  register: patroni1

- debug: var=patroni1.stdout_lines

- name: Start patroni postgresql2 from shell
  shell: patroni patroni_test/postgres2.yml &
  become_user: postgres
  register: patroni2

- debug: var=patroni2.stdout_lines

- name: Copy haproxy.cfg
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy-test.cfg
    owner: root
    group: root
    mode: 0644

- name: Start haproxy
  shell: haproxy -f /etc/haproxy/haproxy-test.cfg &
  register: haproxy

- debug: var=haproxy.stdout_lines
