  - name: Install percona repository package
    apt:
     deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: Install percona-release
#    yum: name=https://repo.percona.com/yum/testing/latest/RPMS/noarch/percona-release-1.0-27.noarch.rpm
    command: yum -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    args:
      warn: no
    when: ansible_os_family == "RedHat"

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"
