---
- name: Install vanila postgresql
  include_tasks: ../../../../tasks/install_pg13.yml

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-13/bin/postgresql-13-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-13
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install ppg12 tools
  include_tasks: ../../../../tasks/install_ppg13_tools.yml
