---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove postgis deb packages
      apt:
        name: postgis25_11
        state: absent
      when: ansible_os_family == "Debian"

    - name: remove postgis rpm packages
      yum:
        name: postgis25_11
        state: absent
      when: ansible_os_family == "RedHat"
