---

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Clean dnf RHEL8
  become: true
  command: dnf clean all -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Disable dnf module for RHEL8
  become: true
  command: dnf module disable postgresql -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql
    - percona-postgresql-13
    - percona-postgresql-all
    - percona-postgresql-client
    - percona-postgresql-client-13
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-server-dev-13
    - percona-postgresql-server-dev-all
  when: ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql-plpython3-13
    - percona-postgresql-plpython3-13-dbgsym
  when:
    - ansible_os_family == "Debian"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-server-dev-all
    - percona-postgresql13
    - percona-postgresql13-contrib
    - percona-postgresql13-devel
    - percona-postgresql13-docs
    - percona-postgresql13-libs
    - percona-postgresql13-llvmjit
    - percona-postgresql13-server
    - percona-postgresql13-test
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: DNF clean RHEL
  command: sudo dnf module disable postgresql -y
  when: ansible_distribution == "RedHat"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql-server-dev-all
      - percona-postgresql13
      - percona-postgresql13-contrib
      - percona-postgresql13-devel
      - percona-postgresql13-libs
      - percona-postgresql13-llvmjit
      - percona-postgresql13-server
      - percona-postgresql13-test
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Initialize Postgres RHEL
  command: /usr/pgsql-13/bin/postgresql-13-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-13
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install vanila postgres source code
  git:

