---
- name: Configure repository
  include_tasks: ../../common/tasks/enable_repo.yml


- name: DNF disable postgresql RHEL
  command: sudo dnf module disable postgresql -y
  when: ansible_distribution == "RedHat"

- name: DNF clean RHEL
  command: sudo dnf clean all -y
  when: ansible_distribution == "RedHat"

- name: Install vanila postgresql
  include_tasks: ../../common/tasks/install_pg11.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-11
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install ppg11 tools
  include_tasks: ../../common/tasks/install_ppg11_tools.yml
