- name: Install vanila postgresql
  include_tasks: ../../../../tasks/install_pg11.yml

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Initialize Postgres RHEL
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  when: ansible_os_family == "RedHat"

- name: Start Postgres RHEL
  service:
    name: postgresql-11
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install ppg11 tools
  include_tasks: ../../../../tasks/install_ppg11_tools.yml
