---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove pgaudit deb packages
      apt:
        name: percona-postgresql-11-pgaudit
        state: absent
      when: ansible_os_family == "Debian"

    - name: remove pgaudit rpm packages
      yum:
        name: percona-pgaudit
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pg_repack deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-postgresql-11-repack
          - percona-postgresql-11-repack-dbgsym
      when: ansible_os_family == "Debian"

    - name: remove pg_repack rpm packages
      yum:
        name: percona-pg_repack11
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove pgbackrest deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-pgbackrest
          - percona-pgbackrest-doc
      when: ansible_os_family == "Debian"

    - name: remove pgbackrest rpm packages
      yum:
        name: percona-pgbackrest
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove patroni deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-patroni
          - percona-patroni-dbgsym
      when: ansible_distribution == "Debian"

    - name: remove patroni rpm packages
      yum:
        name: percona-patroni
        state: absent
      when: ansible_os_family == "RedHat"

    - name: remove patroni ubuntu
      apt:
        name: percona-patroni
        state: absent
      when: ansible_distribution == "Ubuntu"
