---
- name: Clean dnf RHEL8
  become: true
  command: dnf clean all -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Disable dnf module for RHEL8
  become: true
  command: dnf module disable postgresql -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Disable llvm-toolset dnf module for RHEL8
  become: true
  command: dnf module disable llvm-toolset -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: setup epel release
  yum:
    name: epel-release
    update_cache: yes
    state: present

- name: Configure repository
  include_tasks: ../../../../tasks/enable_repo.yml

- name: Percona Platform for PostgreSQL rpm packages for RHEL and additional tools
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - percona-postgresql-client-common
    - percona-postgresql-common
    - percona-postgresql-server-dev-all
    - percona-postgresql11
    - percona-postgresql11-contrib
    - percona-postgresql11-devel
    - percona-postgresql11-libs
    - percona-postgresql11-plpython3
    - percona-postgresql11-pltcl
    - percona-postgresql11-server
    - openssl-devel
    - etcd
    - python3-python-etcd
    - haproxy

- name: Install patroni RPM
  yum:
    name: percona-patroni
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Create /etc/patroni directory
  file:
    path: /etc/patroni
    state: directory

- name: Copy postgresql.yml for patroni service
  copy:
    src: postgresql.yml
    dest: /etc/patroni/postgresql.yml
    owner: root
    group: root
    mode: 0644

- name: Start etcd
  service:
    name: etcd
    state: started
    enabled: yes

- name: Start patroni
  service:
    name: patroni
    state: started
    enabled: yes

- name: Copy haproxy.cfg
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy-test.cfg
    owner: root
    group: root
    mode: 0644

- name: Start haproxy
  command: haproxy -f /etc/haproxy/haproxy-test.cfg &
